import 'package:flutter/material.dart';
import 'package:kenooz_worker_app/core/theming/palette_tokens.dart';

const _diamondPrimary = Color(0xFF7FB3D5);
const _diamondDeep = Color(0xFF3E7CA1);
const _goldAccent = Color(0xFFC9A04E);
const _silverAccent = Color(0xFF8E9AAF);
const _diamondAccent = Color(0xFF7FB3D5);
const _redAccent = Color(0xFFC0392B);

const PaletteTokens diamondLight = PaletteTokens(
  primary: _diamondDeep,
  onPrimary: Color(0xFFFFFFFF),
  secondary: Color(0xFFD6EAF8),
  onSecondary: Color(0xFF0F2230),
  background: Color(0xFFF4F9FC),
  surface: Color(0xFFFFFFFF),
  surfaceElevated: Color(0xFFE8F1F8),
  onSurface: Color(0xFF0F2230),
  onSurfaceMuted: Color(0xFF4A5A66),
  appBarBg: Color(0xFFF4F9FC),
  appBarFg: Color(0xFF0F2230),
  bottomNavBg: Color(0xFFFFFFFF),
  bottomNavSelected: _diamondDeep,
  bottomNavUnselected: Color(0xFF9E9E9E),
  buttonBg: _diamondDeep,
  buttonFg: Color(0xFFFFFFFF),
  buttonDisabled: Color(0xFFE0E0E0),
  textFieldFill: Color(0xFFEAF2F8),
  textFieldBorder: Color(0xFFCFDDE7),
  textFieldFocused: _diamondDeep,
  success: Color(0xFF07A729),
  error: Color(0xFFEF2828),
  warning: Color(0xFFF59E0B),
  divider: Color(0xFFDCE6EE),
  shimmerBase: Color(0xFFE8F1F8),
  shimmerHighlight: Color(0xFFF4F9FC),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens diamondDark = PaletteTokens(
  primary: _diamondPrimary,
  onPrimary: Color(0xFF0A1620),
  secondary: Color(0xFFD6EAF8),
  onSecondary: Color(0xFF0A1620),
  background: Color(0xFF0B141C),
  surface: Color(0xFF152230),
  surfaceElevated: Color(0xFF1E2F3F),
  onSurface: Color(0xFFD6EAF8),
  onSurfaceMuted: Color(0xFFB8C5D1),
  appBarBg: Color(0xFF0B141C),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF060D13),
  bottomNavSelected: _diamondPrimary,
  bottomNavUnselected: Color(0xFF808080),
  buttonBg: _diamondPrimary,
  buttonFg: Color(0xFF0A1620),
  buttonDisabled: Color(0xFF3A3A3A),
  textFieldFill: Color(0xFF152230),
  textFieldBorder: Color(0xFF22364B),
  textFieldFocused: _diamondPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF22364B),
  shimmerBase: Color(0xFF152230),
  shimmerHighlight: Color(0xFF1E2F3F),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens diamondDeepDark = PaletteTokens(
  primary: _diamondPrimary,
  onPrimary: Color(0xFF000000),
  secondary: Color(0xFFD6EAF8),
  onSecondary: Color(0xFF000000),
  background: Color(0xFF000000),
  surface: Color(0xFF0A0A0A),
  surfaceElevated: Color(0xFF141414),
  onSurface: Color(0xFFD6EAF8),
  onSurfaceMuted: Color(0xFF9A9A9A),
  appBarBg: Color(0xFF000000),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF000000),
  bottomNavSelected: _diamondPrimary,
  bottomNavUnselected: Color(0xFF6E6E6E),
  buttonBg: _diamondPrimary,
  buttonFg: Color(0xFF000000),
  buttonDisabled: Color(0xFF1F1F1F),
  textFieldFill: Color(0xFF0A0A0A),
  textFieldBorder: Color(0xFF1F1F1F),
  textFieldFocused: _diamondPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF1F1F1F),
  shimmerBase: Color(0xFF0A0A0A),
  shimmerHighlight: Color(0xFF141414),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);
