import 'package:flutter/material.dart';
import 'package:kenooz_worker_app/core/theming/palette_tokens.dart';

const _goldPrimary = Color(0xFFC9A04E);
const _goldDeep = Color(0xFF986A3E);
const _goldSoft = Color(0xFFE0BBB3);
const _goldAccent = Color(0xFFC9A04E);
const _silverAccent = Color(0xFF8E9AAF);
const _diamondAccent = Color(0xFF7FB3D5);
const _redAccent = Color(0xFFC0392B);

const PaletteTokens goldLight = PaletteTokens(
  primary: _goldDeep,
  onPrimary: Color(0xFFFFFFFF),
  secondary: _goldSoft,
  onSecondary: Color(0xFF1A1A1A),
  background: Color(0xFFFDF7EF),
  surface: Color(0xFFFFFFFF),
  surfaceElevated: Color(0xFFF7ECDF),
  onSurface: Color(0xFF1A1A1A),
  onSurfaceMuted: Color(0xFF525252),
  appBarBg: Color(0xFFFDF7EF),
  appBarFg: Color(0xFF1A1A1A),
  bottomNavBg: Color(0xFFFFFFFF),
  bottomNavSelected: _goldDeep,
  bottomNavUnselected: Color(0xFF9E9E9E),
  buttonBg: _goldDeep,
  buttonFg: Color(0xFFFFFFFF),
  buttonDisabled: Color(0xFFE0E0E0),
  textFieldFill: Color(0xFFF7F2EA),
  textFieldBorder: Color(0xFFE0D6C5),
  textFieldFocused: _goldDeep,
  success: Color(0xFF07A729),
  error: Color(0xFFEF2828),
  warning: Color(0xFFF59E0B),
  divider: Color(0xFFEAE2D2),
  shimmerBase: Color(0xFFF1ECE2),
  shimmerHighlight: Color(0xFFFAF6EE),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens goldDark = PaletteTokens(
  primary: _goldPrimary,
  onPrimary: Color(0xFF1A1A1A),
  secondary: Color(0xFFD4C5A9),
  onSecondary: Color(0xFF1A1A1A),
  background: Color(0xFF0F1610),
  surface: Color(0xFF1C2B24),
  surfaceElevated: Color(0xFF243630),
  onSurface: Color(0xFFD4C5A9),
  onSurfaceMuted: Color(0xFFC0C0C0),
  appBarBg: Color(0xFF0F1610),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF0A110B),
  bottomNavSelected: _goldPrimary,
  bottomNavUnselected: Color(0xFF808080),
  buttonBg: _goldPrimary,
  buttonFg: Color(0xFF1A1A1A),
  buttonDisabled: Color(0xFF3A3A3A),
  textFieldFill: Color(0xFF1C2B24),
  textFieldBorder: Color(0xFF2C3D34),
  textFieldFocused: _goldPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF2C3D34),
  shimmerBase: Color(0xFF1C2B24),
  shimmerHighlight: Color(0xFF243630),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens goldDeepDark = PaletteTokens(
  primary: _goldPrimary,
  onPrimary: Color(0xFF000000),
  secondary: Color(0xFFD4C5A9),
  onSecondary: Color(0xFF000000),
  background: Color(0xFF000000),
  surface: Color(0xFF0A0A0A),
  surfaceElevated: Color(0xFF141414),
  onSurface: Color(0xFFE6D8B8),
  onSurfaceMuted: Color(0xFF9A9A9A),
  appBarBg: Color(0xFF000000),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF000000),
  bottomNavSelected: _goldPrimary,
  bottomNavUnselected: Color(0xFF6E6E6E),
  buttonBg: _goldPrimary,
  buttonFg: Color(0xFF000000),
  buttonDisabled: Color(0xFF1F1F1F),
  textFieldFill: Color(0xFF0A0A0A),
  textFieldBorder: Color(0xFF1F1F1F),
  textFieldFocused: _goldPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF1F1F1F),
  shimmerBase: Color(0xFF0A0A0A),
  shimmerHighlight: Color(0xFF141414),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);
