import 'package:flutter/material.dart';
import 'package:kenooz_worker_app/core/theming/palette_tokens.dart';

const _redPrimary = Color(0xFFE74C3C);
const _redDeep = Color(0xFFC0392B);
const _goldAccent = Color(0xFFC9A04E);
const _silverAccent = Color(0xFF8E9AAF);
const _diamondAccent = Color(0xFF7FB3D5);
const _redAccent = Color(0xFFC0392B);

const PaletteTokens redLight = PaletteTokens(
  primary: _redDeep,
  onPrimary: Color(0xFFFFFFFF),
  secondary: Color(0xFFF5B7B1),
  onSecondary: Color(0xFF1A0A0A),
  background: Color(0xFFFCF4F3),
  surface: Color(0xFFFFFFFF),
  surfaceElevated: Color(0xFFF8E8E5),
  onSurface: Color(0xFF1A0A0A),
  onSurfaceMuted: Color(0xFF5A3A3A),
  appBarBg: Color(0xFFFCF4F3),
  appBarFg: Color(0xFF1A0A0A),
  bottomNavBg: Color(0xFFFFFFFF),
  bottomNavSelected: _redDeep,
  bottomNavUnselected: Color(0xFF9E9E9E),
  buttonBg: _redDeep,
  buttonFg: Color(0xFFFFFFFF),
  buttonDisabled: Color(0xFFE0E0E0),
  textFieldFill: Color(0xFFF8EBE9),
  textFieldBorder: Color(0xFFE5C9C5),
  textFieldFocused: _redDeep,
  success: Color(0xFF07A729),
  error: Color(0xFFEF2828),
  warning: Color(0xFFF59E0B),
  divider: Color(0xFFEED5D2),
  shimmerBase: Color(0xFFF8E8E5),
  shimmerHighlight: Color(0xFFFCF4F3),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens redDark = PaletteTokens(
  primary: _redPrimary,
  onPrimary: Color(0xFF1A0A0A),
  secondary: Color(0xFFF5B7B1),
  onSecondary: Color(0xFF1A0A0A),
  background: Color(0xFF160B0B),
  surface: Color(0xFF241313),
  surfaceElevated: Color(0xFF321B1B),
  onSurface: Color(0xFFF1D5D2),
  onSurfaceMuted: Color(0xFFC0A8A6),
  appBarBg: Color(0xFF160B0B),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF0F0707),
  bottomNavSelected: _redPrimary,
  bottomNavUnselected: Color(0xFF808080),
  buttonBg: _redPrimary,
  buttonFg: Color(0xFFFFFFFF),
  buttonDisabled: Color(0xFF3A2828),
  textFieldFill: Color(0xFF241313),
  textFieldBorder: Color(0xFF3A1F1F),
  textFieldFocused: _redPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF3A1F1F),
  shimmerBase: Color(0xFF241313),
  shimmerHighlight: Color(0xFF321B1B),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens redDeepDark = PaletteTokens(
  primary: _redPrimary,
  onPrimary: Color(0xFF000000),
  secondary: Color(0xFFF5B7B1),
  onSecondary: Color(0xFF000000),
  background: Color(0xFF000000),
  surface: Color(0xFF0A0A0A),
  surfaceElevated: Color(0xFF141414),
  onSurface: Color(0xFFF1D5D2),
  onSurfaceMuted: Color(0xFF9A9A9A),
  appBarBg: Color(0xFF000000),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF000000),
  bottomNavSelected: _redPrimary,
  bottomNavUnselected: Color(0xFF6E6E6E),
  buttonBg: _redPrimary,
  buttonFg: Color(0xFF000000),
  buttonDisabled: Color(0xFF1F1F1F),
  textFieldFill: Color(0xFF0A0A0A),
  textFieldBorder: Color(0xFF1F1F1F),
  textFieldFocused: _redPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF1F1F1F),
  shimmerBase: Color(0xFF0A0A0A),
  shimmerHighlight: Color(0xFF141414),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);
