import 'package:flutter/material.dart';
import 'package:kenooz_worker_app/core/theming/palette_tokens.dart';

const _silverPrimary = Color(0xFF8E9AAF);
const _silverDeep = Color(0xFF6F7782);
const _goldAccent = Color(0xFFC9A04E);
const _silverAccent = Color(0xFF8E9AAF);
const _diamondAccent = Color(0xFF7FB3D5);
const _redAccent = Color(0xFFC0392B);

const PaletteTokens silverLight = PaletteTokens(
  primary: _silverDeep,
  onPrimary: Color(0xFFFFFFFF),
  secondary: Color(0xFFC0C5CE),
  onSecondary: Color(0xFF1A1A1A),
  background: Color(0xFFF6F7F9),
  surface: Color(0xFFFFFFFF),
  surfaceElevated: Color(0xFFEDEFF3),
  onSurface: Color(0xFF1A1A1A),
  onSurfaceMuted: Color(0xFF525252),
  appBarBg: Color(0xFFF6F7F9),
  appBarFg: Color(0xFF1A1A1A),
  bottomNavBg: Color(0xFFFFFFFF),
  bottomNavSelected: _silverDeep,
  bottomNavUnselected: Color(0xFF9E9E9E),
  buttonBg: _silverDeep,
  buttonFg: Color(0xFFFFFFFF),
  buttonDisabled: Color(0xFFE0E0E0),
  textFieldFill: Color(0xFFEEF1F4),
  textFieldBorder: Color(0xFFD7DCE3),
  textFieldFocused: _silverDeep,
  success: Color(0xFF07A729),
  error: Color(0xFFEF2828),
  warning: Color(0xFFF59E0B),
  divider: Color(0xFFE2E5EA),
  shimmerBase: Color(0xFFEDEFF3),
  shimmerHighlight: Color(0xFFF7F8FA),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens silverDark = PaletteTokens(
  primary: _silverPrimary,
  onPrimary: Color(0xFF111418),
  secondary: Color(0xFFC0C5CE),
  onSecondary: Color(0xFF111418),
  background: Color(0xFF101316),
  surface: Color(0xFF1B2026),
  surfaceElevated: Color(0xFF252B33),
  onSurface: Color(0xFFD7DCE3),
  onSurfaceMuted: Color(0xFFC0C0C0),
  appBarBg: Color(0xFF101316),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF0B0E11),
  bottomNavSelected: _silverPrimary,
  bottomNavUnselected: Color(0xFF808080),
  buttonBg: _silverPrimary,
  buttonFg: Color(0xFF111418),
  buttonDisabled: Color(0xFF3A3A3A),
  textFieldFill: Color(0xFF1B2026),
  textFieldBorder: Color(0xFF2A313A),
  textFieldFocused: _silverPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF2A313A),
  shimmerBase: Color(0xFF1B2026),
  shimmerHighlight: Color(0xFF252B33),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);

const PaletteTokens silverDeepDark = PaletteTokens(
  primary: _silverPrimary,
  onPrimary: Color(0xFF000000),
  secondary: Color(0xFFC0C5CE),
  onSecondary: Color(0xFF000000),
  background: Color(0xFF000000),
  surface: Color(0xFF0A0A0A),
  surfaceElevated: Color(0xFF141414),
  onSurface: Color(0xFFD7DCE3),
  onSurfaceMuted: Color(0xFF9A9A9A),
  appBarBg: Color(0xFF000000),
  appBarFg: Color(0xFFFFFFFF),
  bottomNavBg: Color(0xFF000000),
  bottomNavSelected: _silverPrimary,
  bottomNavUnselected: Color(0xFF6E6E6E),
  buttonBg: _silverPrimary,
  buttonFg: Color(0xFF000000),
  buttonDisabled: Color(0xFF1F1F1F),
  textFieldFill: Color(0xFF0A0A0A),
  textFieldBorder: Color(0xFF1F1F1F),
  textFieldFocused: _silverPrimary,
  success: Color(0xFF22C55E),
  error: Color(0xFFEF4444),
  warning: Color(0xFFFBBF24),
  divider: Color(0xFF1F1F1F),
  shimmerBase: Color(0xFF0A0A0A),
  shimmerHighlight: Color(0xFF141414),
  goldAccent: _goldAccent,
  silverAccent: _silverAccent,
  diamondAccent: _diamondAccent,
  redAccent: _redAccent,
);
